### PR TITLE
Add working mode and issue template for subcommittees

### PR DESCRIPTION
**Pull request by tobie**

### CODE REVIEW

**Review by jorydotcom — APPROVED** [review]

**Comment by senthilp** [comment]
LGTM

**Review by candice-womp — APPROVED** [review]

**Comment by kelseyjohnson8** [comment]
Looks good.

**Comment by sumodas** [comment]
+ 1 

Thanks!

—
Sumantro Das
E: sumantro.das@gmail.com
P: (845) 558-8313

**Comment by tobie** [comment]
@KenjiBaheux suggests linking to the definition of facilitator to clarify role (and ability to be an active participant).

**Pull request merged**
